openapi: 3.0.0
info:
  description: Yoda core ruleset containing iRODS and Python rules and policies useful for all Yoda environments.
  contact:
    email: l.r.westerhof@uu.nl
  version: 2.1.0
  title: Yoda core admin stats API
servers:
- url: https://portal.yoda.test/api
  description: Local Yoda development server
security:
- cookieAuth: []
- basicAuth: []
tags:
- name: stats
paths:
  /resource_browse_group_data:
    post:
      tags:
      - stats
      summary: 'Get paginated group data groupname / size

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sort_on:
                  type: string
                  description: Column to sort on ('name', 'modified' or size)
                  default: '''name'''
                  nullable: false
                sort_order:
                  type: string
                  description: Column sort order ('asc' or 'desc')
                  default: '''asc'''
                  nullable: false
                offset:
                  type: integer
                  description: Offset to start browsing from
                  default: '0'
                  nullable: false
                limit:
                  type: integer
                  description: Limit number of results
                  default: '10'
                  nullable: false
                search_groups:
                  type: string
                  description: Search specific groups
                  default: ''''''
                  nullable: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type: string
                    nullable: true
                  data:
                    nullable: true
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
  /resource_full_year_differentiated_group_storage:
    post:
      tags:
      - stats
      summary: 'Return the full range of registered storage data differentiated into vault/research/revision/total.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - group_name
              properties:
                group_name:
                  type: string
                  description: Group that is searched for storage data
                  default: null
                  nullable: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type: string
                    nullable: true
                  data:
                    nullable: true
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
  /resource_category_stats:
    post:
      tags:
      - stats
      summary: 'Collect storage stats of last month for categories.

        Storage is summed up for each category.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type: string
                    nullable: true
                  data:
                    nullable: true
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
  /resource_monthly_category_stats:
    post:
      tags:
      - stats
      summary: 'Collect storage stats for all twelve months based upon categories a user is datamanager of.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type: string
                    nullable: true
                  data:
                    nullable: true
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
components:
  responses:
    status_500:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
    status_400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
  schemas:
    result_error:
      type: object
      properties:
        status:
          type: string
          description: Holds an error ID
        status_info:
          type: string
          description: Holds a human-readable error description
        data:
          description: empty
          nullable: true
          type: object
  securitySchemes:
    cookieAuth:
      in: cookie
      type: apiKey
      name: yoda_session
    basicAuth:
      type: http
      scheme: basic
