openapi: 3.2.0
info:
  description: Yoda core ruleset containing iRODS and Python rules and policies useful for all Yoda environments.
  contact:
    email: l.r.westerhof@uu.nl
  version: 2.1.0
  title: Yoda core Folder API
servers:
- url: https://portal.yoda.test/api
  description: Local Yoda development server
security:
- cookieAuth: []
- basicAuth: []
tags:
- name: Folder
paths:
  /folder_lock:
    post:
      tags:
      - Folder
      summary: Lock a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to lock
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderLock
      x-operation-id-source: derived
  /folder_unlock:
    post:
      tags:
      - Folder
      summary: Unlock a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to unlock
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderUnlock
      x-operation-id-source: derived
  /folder_submit:
    post:
      tags:
      - Folder
      summary: Submit a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to submit
                  default: null
                delete_research_copy:
                  type: boolean
                  description: Whether to delete copy in research space
                  default: 'False'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderSubmit
      x-operation-id-source: derived
  /folder_unsubmit:
    post:
      tags:
      - Folder
      summary: Unsubmit a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to unsubmit
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderUnsubmit
      x-operation-id-source: derived
  /folder_accept:
    post:
      tags:
      - Folder
      summary: Accept a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to accept
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderAccept
      x-operation-id-source: derived
  /folder_reject:
    post:
      tags:
      - Folder
      summary: Reject a folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: Folder to reject
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderReject
      x-operation-id-source: derived
  /folder_get_locks:
    post:
      tags:
      - Folder
      summary: Return a list of locks on a collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - coll
              properties:
                coll:
                  type: string
                  description: (undocumented)
                  default: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type:
                    - string
                    - 'null'
                  data: {}
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
      operationId: postFolderGetLocks
      x-operation-id-source: derived
components:
  responses:
    status_400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
    status_500:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
  schemas:
    result_error:
      type: object
      properties:
        status:
          type: string
          description: Holds an error ID
        status_info:
          type: string
          description: Holds a human-readable error description
        data:
          description: empty
          type:
          - object
          - 'null'
  securitySchemes:
    cookieAuth:
      in: cookie
      type: apiKey
      name: yoda_session
    basicAuth:
      type: http
      scheme: basic
