openapi: 3.0.0
info:
  description: Yoda core ruleset containing iRODS and Python rules and policies useful for all Yoda environments.
  contact:
    email: l.r.westerhof@uu.nl
  version: 2.1.0
  title: Yoda core admin publication_troubleshoot API
servers:
- url: https://portal.yoda.test/api
  description: Local Yoda development server
security:
- cookieAuth: []
- basicAuth: []
tags:
- name: publication_troubleshoot
paths:
  /batch_troubleshoot_published_data_packages:
    post:
      tags:
      - publication_troubleshoot
      summary: 'Wrapper for the batch script for troubleshooting published data packages.

        Runs a subset of the tests since "technicaladmin" is usually more restricted than "rods".

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - requested_package
              - log_file
              - offline
              properties:
                requested_package:
                  type: string
                  description: A string representing a specific data package path or all packages with failed publications.
                  default: null
                  nullable: false
                log_file:
                  type: boolean
                  description: A boolean representing to write results in log.
                  default: null
                  nullable: false
                offline:
                  type: boolean
                  description: A boolean representing whether to perform all checks without connecting to external servers.
                  default: null
                  nullable: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  status_info:
                    type: string
                    nullable: true
                  data:
                    nullable: true
        '400':
          $ref: '#/components/responses/status_400'
        '500':
          $ref: '#/components/responses/status_500'
components:
  responses:
    status_500:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
    status_400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/result_error'
  schemas:
    result_error:
      type: object
      properties:
        status:
          type: string
          description: Holds an error ID
        status_info:
          type: string
          description: Holds a human-readable error description
        data:
          description: empty
          nullable: true
          type: object
  securitySchemes:
    cookieAuth:
      in: cookie
      type: apiKey
      name: yoda_session
    basicAuth:
      type: http
      scheme: basic
